### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by hvelarde** [collective/plone.formwidget.geolocation#5] opened 2016-08-18 22:44 UTC
```
# npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-sed@0.1.1 wants grunt@~0.4

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/hvelarde/personal/smdu.portal/src/smdu.participacao/src/plone.formwidget.geolocation
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hvelarde/personal/smdu.portal/src/smdu.participacao/src/plone.formwidget.geolocation/npm-debug.log
npm ERR! not ok code 0
```

**Comment by l34marr** [comment] 2016-08-19 02:35
See also https://github.com/plone/Products.CMFPlone/issues/1623
What's the convention to deal with such issues? Anything we can do on Plone developers' side?

**Comment by hvelarde** [comment] 2016-08-19 12:54
@l34marr I tried you workaround (`"grunt": ">=0.4.5 <1.0.0"`) but it didn't work here:

```
# npm install 
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
 
> v8-debug@0.7.7 preinstall /home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! tar.unpack untar error /home/hvelarde/.npm/yargs/3.32.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/semver'
npm ERR! error rolling back  node-inspector@0.12.8 { [Error: ENOTEMPTY, rmdir '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/semver']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/semver' }
npm ERR! tar.unpack untar error /home/hvelarde/.npm/parseurl/1.3.1/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/express/4.14.0/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/etag/1.7.0/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/ms/0.7.1/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/rc/node_modules/ini'
npm ERR! error rolling back  grunt-debug-task@0.1.8 { [Error: ENOTEMPTY, rmdir '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/rc/node_modules/ini']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/rc/node_modules/ini' }
npm ERR! v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 preinstall script.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e 'process.exit(0)'
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/hvelarde/personal/smdu.portal/src/smdu.participacao
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, open '/home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/rc/node_modules/strip-json-comments/strip-json-comments.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/hvelarde/personal/smdu.portal/src/smdu.participacao
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/hvelarde/personal/smdu.portal/src/smdu.participacao/node_modules/grunt-debug-task/node_modules/node-inspector/node_modules/rc/node_modules/strip-json-comments/strip-json-comments.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! tar.unpack untar error /home/hvelarde/.npm/deep-extend/0.4.1/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/truncate/1.0.5/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/minimist/1.2.0/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/ini/1.3.4/package.tgz
npm ERR! tar.unpack untar error /home/hvelarde/.npm/v8-profiler/5.6.5/package.tgz
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hvelarde/personal/smdu.portal/src/smdu.participacao/npm-debug.log
npm ERR! not ok code 0
```

**Comment by davilima6** [comment] 2016-08-19 13:13
-    "grunt": "",
+    "grunt": "^0.4.5",

does it for me. If error persists try `npm install -g npm`

**Comment by hvelarde** [comment] 2016-08-19 13:26
@davilima6 doesn't work here the problem seems to be this:

```
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by l34marr** [comment] 2016-08-19 14:19
```
$ cd /usr/bin
$ sudo ln -s nodejs node
### not sure whether the following step is the right way to do
$ npm config set prefix=$HOME/.node_modules_global
```
I know little about the JS world, but that's my workaround for this. FYI.

**Comment by hvelarde** [comment] 2016-08-19 14:35
@l34marr if you read the file mentioned above they talk about the name of the `node` command:

```
nodejs command
--------------

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.

```

**Comment by laulaz** [comment] 2022-06-20 19:54
Seems to be fixed now 👍 , cannot reproduce here ...
Don't hesitate to reopen if you still have the problem!

**Closed by laulaz** 2022-06-20 19:54 UTC
